<?php

/*
 * You can place your custom package configuration in here.
 */
return [
    #quality of life options
    'transaction_observer_active' => false,//activate/deactivate transaction observer
    #must have options
    'sandbox_active' => true,//set true if you work on sandbox / false if in production
    //real path
    'sandbox_public_key' => 'sandbox public key path',
    'sandbox_private_key' => 'sandbox private key path',
    'production_public_key' => 'production public key path',
    'production_private_key' => 'production private key path',
    'sandbox_payment_link' => 'sandbox payment link',
    'production_payment_link' => 'production payment link',
    #merchant account signature - generated by mobilpay.ro for every merchant account
    #semnatura contului de comerciant - mergi pe www.mobilpay.ro Admin -> Conturi de comerciant -> Detalii -> Setari securitate
    'merchant_account_signature' => 'XXXX-XXXX-XXXX-XXXX-XXXX',
    #below is where mobilPay will send the payment result. This URL will always be called first; mandatory
    'confirmUrl' => 'http://your.confirm.url',
    #below is where mobilPay redirects the client once the payment process is finished. Not to be mistaken for a "successURL" nor "cancelURL"; mandatory
    'returnUrl' => 'http://your.return.url',
    #payment currency in ISO Code format; permitted values are RON, EUR, USD, MDL; please note that unless you have mobilPay permission to
    #process a currency different from RON, a currency exchange will occur from your currency to RON, using the official BNR exchange rate from that moment
    #and the customer will be presented with the payment amount in a dual currency in the payment page, i.e N.NN RON (e.ee EUR)
    'currency' => 'RON',
    'invoice-details' => 'invoice details text here',
];
